# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4488a7050a6d425d072d193d8a14db4332b61b5d5aa7042b64f374e78f2a2205e6cb7bc85143c263d5d8e8d5d31b39703a800b30ce8019987d4e03f377b2f0c3

test:
  secret_key_base: 6c5aa3f2d67fa063db7ceb2f95dbd8856e01c95e651e6c481b268835d842fecfe1f314e1268552672801286d635032a33c62d4fd28caac652ed65e07d7c1025d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
